spring.application.name=rest-server


eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzc1ODMzNjg3LCJleHAiOjE3NzU4MzcyODd9.NBkWEddzgSZbz8e6bek6W_YYhPMb8bqgHCxiVB_XyjFgGIipdAIFW70dh2IJPIuTMN634kL5IRz3dhOaBsqBlg
eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzc1ODMzNjg3LCJleHAiOjE3NzU4MzcyODd9.NBkWEddzgSZbz8e6bek6W_YYhPMb8bqgHCxiVB_XyjFgGIipdAIFW70dh2IJPIuTMN634kL5IRz3dhOaBsqBlg